sudo: false
language: java

jdk:
  - openjdk11

install: true
script: mvn -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true clean eclipse:eclipse install

notifications:
  email: false